BIOWDL-528: Make the LICENSE match other BioWDL repo's.
biowdl/scripts pull request #21
Opened 2020-11-18 15:14 UTC by JasperBoom

2020-11-18 16:00 UTC, DavyCats requested changes

2020-11-18 16:00 UTC, DavyCats commented on README.md
> +SASC team at [Leiden University Medical Center](https://www.lumc.nl/).
This is not really a workflow, so this should be changed.

2020-11-18 16:00 UTC, JasperBoom commented on README.md
> +SASC team at [Leiden University Medical Center](https://www.lumc.nl/).
Ah right, nice catch.

2020-11-19 10:11 UTC, DavyCats approved these changes

2020-11-19 10:42 UTC, merged